// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use a placeholder URL during build if the environment variable is not set
    // This is safe because `prisma generate` doesn't actually connect to the database
    url: process.env.POSTGRES_PRISMA_URL || "postgresql://placeholder:placeholder@placeholder:5432/placeholder",
  },
});
